[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

# Mapea la Edge Function a la misma URL que ya usas en el front
[[edge_functions]]
  function = "openrouter-proxy"
  path = "/.netlify/functions/openrouter-proxy"
